version: 0.0
os: linux
files:
  - source: /
    destination: /home/cloudcasts/cloudcasts.io
permissions:
  - object: /home/cloudcasts/cloudcasts.io
    owner: cloudcasts
    group: cloudcasts
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#    - location: scripts/create_test_db.sh
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root